# Generated by Django 4.1.1 on 2022-10-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
