# Generated by Django 4.1.2 on 2022-10-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_event', 'end_event']},
        ),
    ]
