# Generated by Django 4.1.1 on 2022-10-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_end_event_event_start_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
