# Generated by Django 4.1.2 on 2022-10-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
