# Generated by Django 4.1.1 on 2022-10-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_end_event_alter_event_start_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_event', 'end_event']},
        ),
    ]
