# Generated by Django 4.1.1 on 2022-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
