# Generated by Django 4.1.1 on 2022-10-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='today',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
