# Generated by Django 4.1.1 on 2022-10-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='today',
        ),
    ]
