# Generated by Django 4.1.1 on 2022-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='email_address'),
        ),
    ]
